name: Fetch Data and Commit Changes 

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          pip install pandas
      
      - name: Install DVC
        run: |
          pip install dvc


      - name: Execute fetch-data.py
        run: python src/data/fetch-data.py 

      - name: Configure git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          
      - name: Commit/push changes 
        run: |
          git add .
          git commit -m "Automatically fetch data" || echo "No changes to commit"
          git push
          dvc remote modify origin --local access_key_id $DAGSHUB_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DAGSHUB_SECRET_ACCESS_KEY

          git rm --cached data/raw/*.csv
          git commit -m "Stop tracking CSV files in data/raw/"